[package]
name = "zkir-disassembler"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Disassembler for ZK IR v2.1"

[dependencies]
zkir-spec = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
